name: Build MogaiXinji

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode.app/Contents/Developer

      - name: Install ldid
        run: brew install ldid || true

      - name: Build all
        run: bash Scripts/build.sh

      - name: Upload MogaiDylib.dylib
        uses: actions/upload-artifact@v4
        with:
          name: MogaiDylib
          path: build/output/MogaiDylib.dylib

      - name: Upload MogaiConfig.ipa
        uses: actions/upload-artifact@v4
        with:
          name: MogaiConfig-IPA
          path: build/output/MogaiConfig.ipa